# Generated by Django 5.1.6 on 2025-05-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='paused_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
